### ISSUE TITLE
UI hangs when doing app analysis

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#115]
When you run app analysis on a site with a lot of workers/traffic the UI can hang.

My suspected reason is that building all of the graphs/data for the graphs is causing it.

Another thing to note here is that Sisira, in her work for the external UI, has asked that we fill all the data with 0s on the API side. It is still not set in stone, we need to talk to Nitasha and others but if that is something we end up doing, it could simplify our logic significantly on the javascript side

**Comment by ShekharGupta1988** [comment]
Hi Steve,
For the first issue, your guess is right. every graph is an svg element and because of multple svg elements, page size becomes huge and UI becomes sluggish/ hangs. 
There is a possible solution to 
- either not show graphs be default and only show them when wants to see.
or
- only show the first rank detector graph and hide the other detector graphs behind a click

for the second ask, there is a problem doing that in API. Consider following scenarios:
- for availability, if there is no data - should we put 0 or defualt 100. If lets say we put 0 (which is representing no data), then on client side, its impossible to distinguish between an actual 0 and no data.

I think its best at client side to handle no data. Like in our case, we are showing no data as either 0 or 100. In Byron's mockup, he had no data as empty graph with no point. (not sure whether his new mocks has that or not)

**Comment by stevenernst131** [comment]
Yeah, I completely agree. We just had a passing conversation about it but it just doesn't make sense to do it on the API side.

**Comment by stevenernst131** [comment]
However, I am going to look into a way to make the Sia view a little more digestible. Right now there are some detectors that always beep (another issue) and it is hard to figure out what the issue actually is
