### ISSUE TITLE
Vnet issues detector

### ISSUE THREAD

**Issue by PraveenTB** [ShekharGupta1988/AppLensV2#304]
high number of TCP connects and disconnects are usually an indicator of Vnet problems. Talk to Aleks and understand this better to create a detector

**Comment by ShekharGupta1988** [comment]
From Recent Feedback : 

Current site: https://applensv2.azurewebsites.net/sites/NWNRegMNApp/appanalysis/detectors/frebanalysis?startTime=2017-06-05T22:22:00.000Z&endTime=2017-06-06T22:22:00.000Z

Please provide feedback here: On this particular case, the reason the app availability was down was due to a problem with the VNET. The Gateway was under maintenance causing the downtime. 
The gateway upgrade went from 17:28 to 18:06 according to https://jarvis-west.dc.ad.msft.net/FDA67520 and on the following Kusto query we can see some info regarding the VNET was at some point disconnected:
https://wawscus.kusto.windows.net:443/wawsprod [Run in Kusto.Explorer] [Run in Kusto.Explorer on SAW] [Run in Kusto.WebExplorer] 
Vnet 
| where PreciseTimeStamp >= ago(4d)
| where VnetName == "Group NWNRegResources NWNRegVN"
| order by PreciseTimeStamp desc nulls last 

I think it will be good to create a detector that verifies the status of the VNET in case there is one. On this case such a detector would have helped me save a long time and focus at once on the problem. 

Thanks for your good work!
