### ISSUE TITLE
Add support for mega stamps

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppLensV2#317]
Example:
https://applensv2.azurewebsites.net/sites/sfidashboard/appanalysis

https://wawsobserver.azurewebsites.net/sites/sfidashboard

Most detectors will break here because the stamp we get from observer is waws-prod-sn1-061 but the two web workers are on waws-prod-sn1-061c and waws-prod-sn1-061d which have different tenantids. So the front end logs work but any logs on the worker that detectors try to get come back empty

**Comment by ShekharGupta1988** [comment]
Cheap fix:
Get a range of TenantIds using this: 
RoleInstanceHeartbeat | where TIMESTAMP >= ago(1d) | where PublicHost **startswith** "waws-prod-am2-111" | summarize count() by Tenant

(or instead of using startswith, use some regex if possible)

Then in main Query, instead of doing TenantId =~ {tenantId}, use TenantId in ("t1", "t2")
 
In this way, for normal stamps, the perf should not be affected. and we still continue to support sites in ASE as we are relying on TenantIds

**Comment by stevenernst131** [comment]
Two requests had detectors fail because the site was on a mega stamp (I am also assuming that other detectors came back with no data)

"g-faa7c4fd-382b-456c-9a45-2950fd931c24","g-26b8e31a-1d91-492d-8c4a-a31dce8810c9"

Null Ref in deployments and siterestartsettingupdate

**Comment by PraveenTB** [comment]
Before we close, please check this site issue is fixed as well.
both restart detectors should "say the same thing"

https://applensv2.azurewebsites.net/sites/appSIV/appanalysis/detectors/siterestartuserinitiated?startTime=2017-02-28T17:52:00.641Z

https://applensv2.azurewebsites.net/sites/appSIV/appanalysis/detectors/workerprocessrecycle?startTime=2017-02-28T17:52:00.641Z

**Comment by stevenernst131** [comment]
After my tenantid change, it is showing the correct data

![image](https://cloud.githubusercontent.com/assets/7739017/23473617/ba7ccfca-fe65-11e6-8a50-5e5abd5675f7.png)

![image](https://cloud.githubusercontent.com/assets/7739017/23473660/e02c8a26-fe65-11e6-9adb-6817d91f033f.png)
